### ISSUE TITLE
Latest version will not compile

### ISSUE THREAD

**Issue by tcares** [mesosphere/mesos-dns#131] opened 2015-04-20 16:06 UTC
I can't seem to compile this latest version. When I run this:

go get github.com/mesosphere/mesos-dns

I get this error:

src/github.com/mesosphere/mesos-dns/main.go:85: syntax error: unexpected range, expecting {
src/github.com/mesosphere/mesos-dns/main.go:89: syntax error: argument to go/defer must be function call
src/github.com/mesosphere/mesos-dns/main.go:92: non-declaration statement outside function body
src/github.com/mesosphere/mesos-dns/main.go:105: non-declaration statement outside function body
src/github.com/mesosphere/mesos-dns/main.go:106: syntax error: unexpected }

Thanks,
Tim

**Comment by kozyraki** [comment] 2015-04-20 16:18
@jdef Can you take a quick look at this? I am in meetings for a while. Thanks

**Comment by tcares** [comment] 2015-04-20 16:22
If I go back to commit 42b8542, it will compile.

**Comment by kozyraki** [comment] 2015-04-20 16:27
@tcares can you please try the following
cd $GOPATH/src/github.com/mesosphere/mesos-dns
make updatedeps
make build

Let me know what happens

**Comment by tcares** [comment] 2015-04-20 16:30
Okay, tried that but updatedeps got this:

[vagrant@node1 mesos-dns]$ make updatedeps
--> Updating build dependencies
godep: not in manifest: .
godep: no packages can be updated
make: *** [updatedeps] Error 1

**Comment by kozyraki** [comment] 2015-04-20 18:17
Very interesting. I see the same issue on my mac but not on a google compute engine instance where I set up go from scratch. So, it's some go craziness. 

I will investigate more and post a solution in a few hours.

**Comment by tcares** [comment] 2015-04-20 18:20
Sure, no problem. As I said above, commit 42b8542 works so something in the last few checkins seems to have caused the problem.

**Comment by joerg84** [comment] 2015-04-20 18:23
Building from scratch on mac works for me (go1.4.1)...

**Comment by tcares** [comment] 2015-04-20 18:25
Okay, I'm running go 1.4.2 on my mac.

Tims-MacBook-Pro:~ tcares$ go version
go version go1.4.2 darwin/amd64

**Comment by tcares** [comment] 2015-04-20 18:26
I'm actually trying to run this inside of a vagrant VM - it's CentOs 7.0. It looks like it's running an older version of go:

[vagrant@node1 outyet]$ go version
go version go1.3.3 linux/amd64

**Comment by kozyraki** [comment] 2015-04-20 19:02
@tcares I still don't know what the problem is. But on my mac, I removed go (which was installed with brew before) then installed it again (with the pkg file from golang.org) and now it all compiles and runs properly. I am not sure how my previous installation got messed but I was seeding similar messages before "godep: not in manifest: .".

**Comment by tcares** [comment] 2015-04-20 20:27
It's definitely related to version of go. The yum repos for Centos 7.0 have go version 1.3.3 as latest. No matter what I do, I get those errors with that version of go. If I download the binaries directly from golang.org to get latest (1.4.2), I do not get those errors and I can compile mesos-dns with no issues.

**Comment by kozyraki** [comment] 2015-04-20 21:55
Merged with #134

**Closed by kozyraki** 2015-04-20 21:55 UTC

**Comment by kozyraki** [comment] 2015-04-20 23:36
See issue and fix for #135

**Comment by kozyraki** [comment] 2015-04-20 23:36
@tcares This should be fixed now.

**Comment by tcares** [comment] 2015-04-21 00:03
Confirmed fixed. Thanks!
