### ISSUE TITLE
RFC952 MaxLength

### ISSUE THREAD

**Issue by jensendw** [mesosphere/mesos-dns#175] opened 2015-06-19 15:24 UTC
I guess this is more of a question as to why you guys picked RFC952 for DNS instead of RFC1035.  The 24 character maximum length is causing us some headaches.  We are running into a problem where we have DNS naming collisions due to the length of appid's in Marathon.  For example

/somereallllllyyyylongappname/stage/1.91-snapshot

I attempted to modify MaxLength in rfc952.go and recompiled but that did not appear to solve my issue.  

Case and point, is there a technical reason why you choose RFC952 or should I just build in my own support for longer names.  I feel like in the long run this will be an issue for other people as well.

**Comment by tsenart** [comment] 2015-06-19 15:44
Hi @jensendw,

I'm sorry but we're missing some context. Can you link to the file you modified?

Thanks,
Tomás

**Comment by jensendw** [comment] 2015-06-19 15:46
sure

https://github.com/jensendw/mesos-dns/blob/master/records/labels/dns952.go#L3

**Comment by tsenart** [comment] 2015-06-19 16:12
From: https://tools.ietf.org/html/rfc1035#section-3.1
> To simplify implementations, the total length of a domain name (i.e.,
label octets and label length octets) is restricted to 255 octets or
less.

The number of characters that fit into 255 bytes entirely depends on the encoding being used.
I don't immediately see how you're noticing a **24** character limit but we might have a bug.

Would you consider `/somereallllllyyyylongappname/stage/1.91-snapshot` a good test case or can you provide a better one?

**Comment by tsenart** [comment] 2015-06-19 16:14
Oh wait, I thought I was looking at our fork, but it was yours.

**Comment by tsenart** [comment] 2015-06-19 16:19
I'll defer to @jdef to provide context as to why we went with RFC952 and not RFC1035. Note, however, that things could get even more complicated with https://tools.ietf.org/html/rfc3490

**Comment by tsenart** [comment] 2015-06-19 16:24
https://godoc.org/golang.org/x/net/idna#ToASCII

**Comment by jensendw** [comment] 2015-06-19 20:11
@tsenart I'm not quite following the idna link, based on the RFC's that it appears to implement the character limit is 63, however, mesos-dns still cuts of appid's at 24 characters as per RFC952.

**Comment by moderation** [comment] 2015-06-19 20:50
Is this issue related? https://github.com/mesosphere/mesos-dns/issues/149 @kozyraki

**Comment by jensendw** [comment] 2015-06-19 22:18
yes

**Comment by tsenart** [comment] 2015-06-20 11:34
Duplicate of #149.

**Closed by tsenart** 2015-06-20 11:34 UTC
Labels: duplicate
