### ISSUE TITLE
undefined: zk.StateSyncConnected when running go get

### ISSUE THREAD

**Issue by F21** [mesosphere/mesos-dns#180] opened 2015-07-03 05:03 UTC
I am following the instructions to build mesos-dns here: http://mesosphere.github.io/mesos-dns/docs/

When using `go get` to get mesos-dns, I get this error:

```
$ go get github.com/mesosphere/mesos-dns
# github.com/mesos/mesos-go/detector/zoo
go/src/github.com/mesos/mesos-go/detector/zoo/client.go:273: undefined: zk.StateSyncConnected
```

**Comment by hanwang** [comment] 2015-07-06 14:06
Running to this error as well when using a Dockerfile that used to previously work.

**Comment by sttts** [comment] 2015-07-06 14:11
@F21 is working on a pull request. 

Note that using godeps should work fine. The problem is that `go get` does not honor the defined versions of the GoDeps/GoDeps.json file.

**Comment by hanwang** [comment] 2015-07-07 21:48
I have install godeps on the Dockerfile images before I attempt to "go get github.com/mesosphere/mesos-dns" and it's still giving this error. Is there a workaround?

**Comment by kozyraki** [comment] 2015-07-07 21:57
I think everyone is running into
https://github.com/mesos/mesos-go/issues/143

Have you tried using godep to get an older version of go-zookeper?

**Comment by hanwang** [comment] 2015-07-07 22:15
I'm not very really familiar with GO, how would I be able to do that?

**Comment by kozyraki** [comment] 2015-07-07 22:28
make restoredeps 
make build

**Comment by tsenart** [comment] 2015-08-11 10:09
Fixed by https://github.com/mesosphere/mesos-dns/pull/221

**Closed by tsenart** 2015-08-11 10:09 UTC
