### ISSUE TITLE
Fix mesos deployments to get meaningful names

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns#38] opened 2014-12-09 06:56 UTC
Right now, many frameworks register with very long names (e.g., marathon-0.7.5). Moreover, tasks often have non meaningful names (e.g., redis1.a6976659-7f62-11e4-b523-56847afe9799). We should recommend meaningful names for frameworks and tasks so that service discovery through DNS can be useful.

**Comment by mindscratch** [comment] 2015-01-23 18:19
Submitted a pull request to update the docs to mention the issue of naming (https://github.com/mesosphere/mesos-dns/pull/66).

**Comment by tarnfeld** [comment] 2015-01-25 17:13
Perhaps it's worth looking at [MESOS-2208](https://issues.apache.org/jira/browse/MESOS-2208) and seeing if we can pull out friendlier names from those protobufs _if set_? It looks like they are available in the state.json blobs.

**Comment by kozyraki** [comment] 2015-01-25 17:15
Yes, this service discovery info will be very useful. We will start using it in Mesos-DNS as soon as it makes it into a Mesos release (hopefully 0.22.0). 

We still have to decide what naming schemes to support based on this information. I suspect that we will have to support a few alternatives. For example some prefer something simple (e.g. search.mesos), while others some more complex (search.prod.europe.mesos). If you have preferences, please let us know.

**Comment by tarnfeld** [comment] 2015-01-25 17:17
Yeah that's a good point r.e naming strategy. One of the points I brought up on the diff review was that different people will have different levels of "environment" metadata, and IMO the "environment" value should have been a `repeated` list of strings.

I think it's best to just replicate the values that are defined in the `DiscoveryInfo` proto.

**Comment by tsenart** [comment] 2015-08-11 08:36
The scope of this issue is just documentation as we can only recommend naming best practices for framework developers.

**Comment by tsenart** [comment] 2015-08-11 10:02
Duplicate of #168

**Closed by tsenart** 2015-08-11 10:02 UTC
Labels: documentation, help wanted, question
